### ISSUE TITLE
Cannot connect to server

### ISSUE THREAD

**Issue by hinhthoi** [scith/BoxBilling_Proxmox#6]
Hi, when i create a new proxmox server (very first step), then i click test connection, it say internal server error.

Could you upload a screenshot when you create a "New Server"?

Thanks!

**Comment by scith** [comment]
Hello :)
Is your proxmox server online? The "test connection" button tries to connect to the API (using the IP or hostname and password provided)
If there is an error, it should appear in the php error log (in the bb-data folder). Can you see anything related to this?

**Comment by hinhthoi** [comment]
Hi, thank you very much. I will check it about 3 hours later. I'm on another duty right now. THANKS!!!!

**Comment by hinhthoi** [comment]
Hi scith, i have tested again now and see it can connect successfully. However, i don't see a form so that customers can fill in the required hostname for the VPS they are signing up

**Comment by hinhthoi** [comment]
There was nothing in the php error log, perhaps because yesterday there was some network issues. I'm having a budget dedicated server just for testing proxmox

**Comment by scith** [comment]
Hi, the connectivity should have been the problem yes (hence the failed test connection)
For the hostname, that could be added I think. However, see this issue that is severly limiting the automation at the moment: https://github.com/scith/BoxBilling_Proxmox/issues/2

I didn't manage to retrieve the container IP on creation :cry: For this reason, I can't transmit the IP of the server to the client on creation... If you can help let me know. Ill close this issue for now
